name: Create or Deploy LiveKit Cloud Agent Manually
on:
  workflow_dispatch:
    inputs:
      operation:
        description: 'Which operation to run'
        required: true
        type: choice
        options:
          - create
          - deploy
        default: 'create'

jobs:
  create-agent:
    runs-on: ubuntu-latest
    environment: .
    if: github.event.inputs.operation == 'create'
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: write
      pull-requests: write
      actions: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Create LiveKit Cloud Agent
        id: livekit
        uses: livekit/deploy-action@v2
        env:
          LIVEKIT_URL: ${{ secrets.LIVEKIT_URL }}
          LIVEKIT_API_KEY: ${{ secrets.LIVEKIT_API_KEY }}
          LIVEKIT_API_SECRET: ${{ secrets.LIVEKIT_API_SECRET }}
          SECRET_LIST: ${{ secrets.SECRET_LIST }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          OPERATION: create
          WORKING_DIRECTORY: .
      - name: Create Pull Request # create a pull request to add the newly created livekit.toml
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            ./livekit.toml
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: cloud-agent-${{ github.run_id }}
          title: "Add LiveKit agent config"
          commit-message: "Add LiveKit agent config"
          body: |
            This PR adds the LiveKit agent configuration

          base: main
          delete-branch: true
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: cloud-agent-${{ github.run_id }}
      - name: Status Check # block until the agent is in the 'Running' state
        uses: livekit/deploy-action@v2
        env:
          LIVEKIT_URL: ${{ secrets.LIVEKIT_URL }}
          LIVEKIT_API_KEY: ${{ secrets.LIVEKIT_API_KEY }}
          LIVEKIT_API_SECRET: ${{ secrets.LIVEKIT_API_SECRET }}
        with:
          OPERATION: status-retry
          WORKING_DIRECTORY: .
          TIMEOUT: 5m
  deploy-agent:
    runs-on: ubuntu-latest
    environment: .
    if: github.event.inputs.operation == 'deploy'
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Deploy LiveKit Cloud Agent
        uses: livekit/deploy-action@v2
        env:
          LIVEKIT_URL: ${{ secrets.LIVEKIT_URL }}
          LIVEKIT_API_KEY: ${{ secrets.LIVEKIT_API_KEY }}
          LIVEKIT_API_SECRET: ${{ secrets.LIVEKIT_API_SECRET }}
        with:
          OPERATION: deploy
          WORKING_DIRECTORY: .